config/routes.rb
Petyard::Application.routes.draw do
  get 'players_online' => 'home#players_online', :as => :players_online
  get 'map' => 'home#map', :as => :map

  resources :projects do
    member do
      get 'join'
    end

    resources :project_memberships
  end

  resources :mod_messages

  resources :forum_categories, :except => [:show]

  resources :forums do
    resources :topics, :except => [:index] do
      resources :posts, :except => [:index, :show]
    end
  end

  get 'forums/:forum_id/:topic_id/new' => 'posts#new', :as => :new_forum_topic_post
  get 'forums/:forum_id/:topic_id/:id/edit' => 'posts#edit', :as => :edit_forum_topic_post

  get 'forums/:forum_id/new' => 'topics#new', :as => :new_forum_topic
  get 'forums/:forum_id/:id/edit' => 'topics#edit', :as => :edit_forum_topic
  get 'forums/:forum_id/:id' => 'topics#show', :as => :forum_topic
  put 'forums/:forum_id/:id' => 'topics#update'
  delete 'forums/:forum_id/:id' => 'topics#destroy'

  get 'register' => 'users#new', :as => :register
  get 'account' => 'users#edit', :as => :account
  match 'account/:id/remove_avatar' => 'users#remove_avatar', :as => :remove_avatar
  get 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  get 'profile/:id' => 'users#show', :as => :user
  put 'profile/:id' => 'users#update'
  delete 'profile/:id' => 'users#destroy'
  resources :users
  resources :user_sessions

  resources :ranks

  get 'notify' => 'home#notify', :as => :notify

  resources :features
  
  root :to => 'home#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :forum_id, :locked, :sticky, :title, :user_id

  belongs_to :user
  belongs_to :forum
  has_many :posts, :dependent => :destroy

  validates :title, :presence => { :message => "* Your topic must have a title." }

  default_scope order("latest_post_id desc")
  scope :notstickied, where(:sticky => false)
  scope :stickied, where(:sticky => true)

  def to_param
    permalink
  end

  def editable?
    Time.now < (created_at + 30.seconds) || Time.now < (updated_at + 30.seconds)
  end

  def last_post
    self.posts.last
  end

  def replies
    self.posts.count - 1
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter(:except => :show) { |b| b.require_power 1 }
  before_filter :set_page_id, :find_players_online

  # GET /topics
  # GET /topics.json
  def index
    @forum = Forum.find_by_permalink(params[:forum_id])
    
    redirect_to @forum
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @forum = Forum.includes(:topics).find_by_permalink(params[:forum_id])
    @topic = @forum.topics.includes(:posts).find_by_permalink(params[:id])
    @posts = @topic.posts.order("id asc")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @forum = Forum.find_by_permalink(params[:forum_id])
    @topic = @forum.topics.build
    @post = @topic.posts.build

    if @forum.accessibility == "staff-only"
      require_power(2)
    end

    if @forum.accessibility == "read-only" || @forum.accessibility == "reply-only"
      require_power(4)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @forums = Forum.all
    @forum = Forum.find_by_permalink(params[:forum_id])
    @topic = @forum.topics.find_by_permalink(params[:id])
    @post = @topic.posts.first

    unless (@topic.editable? && current_user == @topic.user) || current_user.has_power(3)
      flash[:topic_error] = "You cannot edit a topic after 30 seconds."
      redirect_to forum_topic_path(@forum, @topic)
    end
  end

  # POST /topics
  # POST /topics.json
  def create
    @forum = Forum.find_by_permalink(params[:forum_id])
    @topic = @forum.topics.build(params[:topic])
    @post = Post.new(params[:post])

    @topic.user = current_user
    @topic.latest_post_id = @post.id
    @post.user = current_user
    @post.topic = @topic
    @post.title = @topic.title
    @topic.permalink = create_permalink(params[:topic][:title])

    respond_to do |format|
      if @post.save && @topic.save
        @topic.latest_post_id = @post.id
        @topic.save
        format.html { redirect_to forum_topic_path(@forum, @topic), notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: [@topic.errors, @post.errors], status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @forum = Forum.find_by_permalink(params[:forum_id])
    @topic = Topic.find_by_permalink(params[:id])
    @post = @topic.posts.order("id asc").first

    @topic.permalink = create_permalink(params[:topic][:title]) if params[:update_permalink]

    respond_to do |format|
      if @topic.update_attributes(params[:topic]) && @post.update_attributes(params[:post])
        @post.title = @topic.title
        @post.save
        format.html { redirect_to forum_topic_path(@forum, @topic), notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @forum = Forum.find_by_permalink(params[:forum_id])
    @topic = @forum.topics.find_by_permalink(params[:id])

    unless (@topic.editable? && current_user == @topic.user) || current_user.has_power(4)
      flash[:topic] = "You cannot delete a topic after 30 seconds."
      redirect_to [@forum, @topic]
      return false
    end

    @topic.destroy

    respond_to do |format|
      format.html { redirect_to @forum }
      format.json { head :no_content }
    end
  end

  protected

  def set_page_id
    @page_id = 'forums'
  end

  def find_players_online
    @players_online = get_players_online
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for([@forum, @topic], :html => { :multipart => true }, :validate => true ) do |f| %>

  <div class="contentbox">
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <% if controller.action_name == "edit" %>
      <div>
        <%= check_box_tag :update_permalink, true, :checked => true %>
        <%= label_tag :update_permalink, "Update permalink?" %> <small>(<%= forum_url(@forum) %>/<span class="highlight">this-is-the-permalink</span>)</small>
        <br /><br />
      </div>
      <% if can_access(3) %>
        <div class="field">
          <%= f.label :forum_id %><br />
          <%= f.select :forum_id, @forums.map {|m| [m.title, m.id]} %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="contentbox">
    <div class="field">
      <%= fields_for @post do |p| %>
        <%= p.text_area :body, :class => 'ckeditor' %>
      <% end %>
    </div>
  </div>

  <% if can_access(3) %>
    <div class="contentbox">
      <div class="mod-options">
        <%= f.check_box :locked %> <%= f.label :locked %>
        <%= f.check_box :sticky %> <%= f.label :sticky %>
        <% if @post.hidden %>
          <%= hidden_field_tag 'post[hidden]', 0, :id => nil %><%= check_box_tag 'post[hidden]', 1, :checked => true %> <%= label_tag 'post[hidden]', "Hidden" %>       
        <% else %> 
          <%= hidden_field_tag 'post[hidden]', 0, :id => nil %><%= check_box_tag 'post[hidden]', 1 %> <%= label_tag 'post[hidden]', "Hidden" %>    
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="contentbox">
    <div class="actions">
      <% if controller.action_name == "new" || controller.action_name == "create" %>
        <%= f.submit "Create" %>
      <% else %>
        <%= f.submit "Save" %>
      <% end %>
      <br /><br />
      <p class="align-center">
        <% if controller.action_name == "new" || controller.action_name == "create" %>
          <%= link_to "Cancel", @forum %>
        <% else %>
          <%= link_to "Cancel", [@forum, @topic] %>
        <% end %>
      </p>
    </div>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="form forum-form">
  <h2>Edit topic</h2>
    <%= render 'form' %>
</div>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Locked</th>
    <th>Sticky</th>
    <th>User</th>
    <th>Forum</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= topic.locked %></td>
    <td><%= topic.sticky %></td>
    <td><%= topic.user_id %></td>
    <td><%= topic.forum_id %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<div class="form forum-form">
  <h2>New topic</h2>
    <%= render 'form' %>
</div>

app/views/topics/show.html.erb
<p><%= link_to "Forums home", forums_path %> &raquo; <%= link_to @forum.title, @forum %> &raquo;</p>

<% unless @forum.accessibility == "read-only" && !can_access(2) %>
  <% if can_access(1) %>
    <span class="forum-buttons">
      <% unless @topic.locked? %>
        <%= link_to "Add reply", new_forum_topic_post_path(@forum, @topic), :class => "button" %>
      <% else %>
        <%= link_to "Locked", new_forum_topic_post_path(@forum, @topic), :class => "button disabled" %>
      <% end %>
    </span>
  <% end %>
<% end %>

<h2><%= @topic.title %></h2>
<!-- <ul class="pagination">
  <li class="disabled">&laquo; Prev</li>
  <li class="disabled">1</li>
  <li><a href="#">2</a></li>
  <li><a href="#">3</a></li>
  <li><a href="#">Next &raquo;</a></li>
</ul> -->
<% @posts.each do |post| %>
  <div class="post">
    <p class="tag">
      <span class="float-right">
        <%= link_to "Quote", new_forum_topic_post_path(@forum, @topic, :quote => post.id) if can_access(1) && !post.hidden %>
        <% if can_edit(post) %>
          <% if post == post.topic.posts.first %>
            <%= " | " unless post.hidden? %>
            <%= link_to("Edit", edit_forum_topic_path(@forum, @topic)) %>
            <%=raw " | " + link_to("Delete", forum_topic_path(@forum, @topic), method: :delete, data: { confirm: 'Delete entire topic (this is permanent)?' }) %>
          <% else %>
            <%= " | " unless post.hidden? %>
            <%= link_to("Edit", edit_forum_topic_post_path(@forum, @topic, post)) %>
            <%=raw " | " + link_to("Delete", forum_topic_post_path(@forum, @topic, post), method: :delete, data: { confirm: 'Delete post (this is permanent)?' }) %>
          <% end %>
        <% end %>
      </span>
      <%= link_to "", {}, :name => post.id %><%= link_to post.title, :anchor => post.id %>&nbsp;&nbsp;&nbsp;posted on <%= post.posted %>
    </p>
    <%= render 'users/userinfo', :user => post.user %>
    <div class="post-content">
      <%=sanitize post.content %>
    </div>
    <div class="buffer"></div>
  </div>
<% end %>
<!-- <ul class="pagination">
  <li class="disabled">&laquo; Prev</li>
  <li class="disabled">1</li>
  <li><a href="#">2</a></li>
  <li><a href="#">3</a></li>
  <li><a href="#">Next &raquo;</a></li>
</ul> -->
<% unless @forum.accessibility == "read-only" && !can_access(2) %>
  <% if can_access(1) %>
    <span class="forum-buttons">
      <% unless @topic.locked? %>
        <%= link_to "Add reply", new_forum_topic_post_path(@forum, @topic), :class => "button" %>
      <% else %>
        <%= link_to "Locked", new_forum_topic_post_path(@forum, @topic), :class => "button disabled" %>
      <% end %>
    </span>
  <% end %>
<% end %>

<br /><br /><br />
<%= render 'forums/active_users' %>