config/routes.rb
Petyard::Application.routes.draw do
  get 'players_online' => 'home#players_online', :as => :players_online
  get 'map' => 'home#map', :as => :map

  resources :projects do
    member do
      get 'join'
    end

    resources :project_memberships
  end

  resources :mod_messages

  resources :forum_categories, :except => [:show]

  resources :forums do
    resources :topics, :except => [:index] do
      resources :posts, :except => [:index, :show]
    end
  end

  get 'forums/:forum_id/:topic_id/new' => 'posts#new', :as => :new_forum_topic_post
  get 'forums/:forum_id/:topic_id/:id/edit' => 'posts#edit', :as => :edit_forum_topic_post

  get 'forums/:forum_id/new' => 'topics#new', :as => :new_forum_topic
  get 'forums/:forum_id/:id/edit' => 'topics#edit', :as => :edit_forum_topic
  get 'forums/:forum_id/:id' => 'topics#show', :as => :forum_topic
  put 'forums/:forum_id/:id' => 'topics#update'
  delete 'forums/:forum_id/:id' => 'topics#destroy'

  get 'register' => 'users#new', :as => :register
  get 'account' => 'users#edit', :as => :account
  match 'account/:id/remove_avatar' => 'users#remove_avatar', :as => :remove_avatar
  get 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  get 'profile/:id' => 'users#show', :as => :user
  put 'profile/:id' => 'users#update'
  delete 'profile/:id' => 'users#destroy'
  resources :users
  resources :user_sessions

  resources :ranks

  get 'notify' => 'home#notify', :as => :notify

  resources :features
  
  root :to => 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation, :avatar

  authenticates_with_sorcery!

  belongs_to :rank
  has_many :topics, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :mod_messages, :dependent => :destroy
  has_many :project_memberships
  has_many :projects, :through => :project_memberships
  has_attached_file :avatar, :styles => { :large => "100x100>", :medium => "60x60>", :small => "35x35>" }, :dependent => :destroy
  
  validates :password, :presence => { :message => "* You must choose a password." }, :on => :create
  validates :password, :confirmation => { :message => "* Password confirmation does not match password." }
  validates :username, :presence => { :message => "* You must enter your Minec\/^[^ ]+$\/raft username." }
  validates :username, :uniqueness => { :case_sensitive => false, :message => "* This username has already been taken." }
  validates :username, :format => { :with => /^[^\s]+$/, :message => "* Your Minecraft username may not have spaces." }
  validates_attachment :avatar, :content_type => { :content_type => "image/jpg", :content_type => "image/png" }, :size => { :in => 0..30.kilobytes }

  def to_param
    username
  end

  def minotar(size)
    if avatar.blank?
      "https://minotar.net/avatar/#{username}/#{size}"
    else
      case size
      when 35
        avatar.url(:small)
      when 60
        avatar.url(:medium)
      when 100
        avatar.url(:large)
      else
        avatar.url(:large)
      end
    end
  end

  def has_power(powercheck)
    rank.power >= powercheck || false
  end

  def unverified?
    rank == Rank.find_by_title('unverified')
  end

  def self.find_by_username(username)
    find(:first, :conditions => ["LOWER(username) = ?", username.downcase])
  end

  def project_role(project)
    if project_memberships.find_by_project_id(project.id)
      return self.project_memberships.find_by_project_id(project.id).role
    else
      return false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter(:only => [:edit, :update, :remove_avatar]) { |b| b.require_power 0 }
  before_filter(:only => [:index, :destroy]) { |b| b.require_power 5 }
  before_filter :find_players_online

  # GET /users
  # GET /users.json
  def index
    @ranks = Rank.includes(:users).order('power asc').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if !params[:id]
      @user = current_user
    else
      @user = User.find_by_username(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    if !logged_in? or current_user.has_power(4)
      @user = User.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
    else
      redirect_to account_path
    end
  end

  # GET /users/1/edit
  def edit
    if !current_user.has_power(5) or !params[:id]
      @user = current_user
    else
      @user = User.find_by_username(params[:id])
    end
    @ranks = Rank.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        auto_login(@user)
        format.html { redirect_to notify_path, notice: "Your account has been created. However, you must verify your account with an administrator to complete activation. You may do so by connecting to <span class='highlight'>petyard.net</span> in Minecraft.<br /><br /><a href='#{user_path(@user)}'>Continue to your profile</a>" }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find_by_username(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:success] = "Account updated."
        format.html { redirect_to @user }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find_by_username(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def remove_avatar
    @user = User.find_by_username(params[:id])

    if @user == current_user || @user.has_power(4)
      @user.avatar = nil
      @user.save
    end

    redirect_to account_path
  end

  protected

  def find_players_online
    @players_online = get_players_online
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= form_for(@user, :html => { :multipart => true }, :validate => true) do |f| %>
<div class="contentbox">
  <div class="field">
    <%= f.label :username %><br />
    <% if current_user.has_power(4) %>
      <%= f.text_field :username %>
    <% else %>
      <%= f.text_field :username, :disabled => true %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
</div>
<% if can_access(4) %>
  <div class="contentbox">
    <div class="field align-center">
      <%= f.label :rank_id %><br />
      <%= f.select :rank_id, @ranks.map {|m| [m.title, m.id]} %>
    </div>
  </div>
<% end %>
<div class="contentbox">
  <div class="field">
    <%= f.label :title, "Forum title" %><br />
    <%= f.text_field :title %>
  </div>
</div>
<div class="contentbox">
  <div>
    <%= image_tag @user.minotar(60), :class => 'float-left' %>
    <%= f.label :avatar, "Avatar" %>&nbsp;&nbsp;<%= link_to("remove", remove_avatar_path(@user), method: :delete, data: { confirm: 'Remove avatar (this is permanent)?' }) if !@user.avatar.blank? %><br />
    <%= f.file_field :avatar %><br />
    <small>(100px &times; 100px max, 30 kilobytes max, jpg or png)</small>
  </div>
</div>
<div class="contentbox">
  <div class="actions">
    <%= f.submit "Save" %><br /><br />
    <p class="align-center"><%= link_to "Cancel updates", current_user %></p>
  </div>
</div>
<% end %>

app/views/users/_new_form.html.erb
<%= form_for(@user, :validate => true) do |f| %>
  <div class="field">
    <%= f.label :username, "Username (your Minecraft name)" %><br />
    <%= f.text_field :username, :value => params[:username] %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/users/_userinfo.html.erb
<ul class="userinfo">
  <li><%= link_to user.username, user_path(user) %></li>
  <li><%= image_tag user.minotar(100), :alt => user.username %></li>
  <li><%= user.title %></li>
  <li>
    <% if user.rank.icon? %>
      <%= image_tag user.rank.icon, :alt => user.rank.title.capitalize %>
    <% else %>
      <em><%= user.rank.title.capitalize %></em>
    <% end %>
  </li>
  <% if @players_online && @players_online.include?(user.username) %>
    <li><%= image_tag "in-game.png" %></li>
  <% end %>
</ul>

app/views/users/_userinfo_template.html.erb
<ul class="userinfo">
  <li><%= link_to params[:id], user_path(params[:id]) %></li>
  <li><%= image_tag "https://minotar.net/avatar/#{params[:id]}/100", :alt => params[:id] %></li>
</ul>

app/views/users/edit.html.erb
<div class="form">
  <h2>Edit account</h2>
    <%= render 'edit_form' %>
</div>

app/views/users/index.html.erb
<% content_for :admin do %>
  <% if can_access(4) %>
    <div id="admin-actions">
      <p>Admin actions for this page:</p>
      <p><%= link_to "Create user", new_user_path %></p>
    </div>
  <% end %>
<% end %>

<h2>Users</h2>

<% unless @ranks.empty? %>
  <% @ranks.each do |rank| %>
    <% if rank.icon? %>
      <%= link_to image_tag(rank.icon, :alt => rank.title.capitalize), edit_rank_url(rank) %>
    <% else %>
      <em><%= link_to rank.title.capitalize, edit_rank_url(rank) %></em>
    <% end %>
    <% unless rank.users.empty? %>
      <% rank.users.each do |user| %>
        <div class="contentbox">
          <p class="float-right">
            <small>(<%= link_to "Edit", edit_user_path(user) %> <%=raw (" | " + link_to("Delete", user, method: :delete, data: { confirm: "Delete this user (this is permanent)?" })) unless user.has_power(5) %>)</small>
          </p>
          <%= link_to image_tag(user.minotar(35), :class => "float-left", :alt => user.username), user %>
          <h3><%= link_to user.username, user %></h3>  
        </div>
      <% end %>
    <% else %>
      <div class="contentbox">
        None.
      </div>
    <% end %>
  <% end %>
<% else %>
  <div class="contentbox">
    There are no ranks to put users in! <%= link_to "Create some ranks", ranks_url %>, first.
  </div>
<% end %>

app/views/users/new.html.erb
<div class="form">
  <h2>Create an account</h2>
  <div class='contentbox'>
    <%= render 'new_form' %>
  </div>
</div>

app/views/users/show.html.erb
<div id="profile">
  <% if @user %>
    <% content_for :admin do %>
      <% if can_access(4) && @user != current_user %>
        <div id="admin-actions">
          <p>Admin actions for this page:</p>
          <p>
            <%= link_to "Edit #{@user.username}'s account", edit_user_path(@user) %>
          </p>
        </div>
      <% end %>
    <% end %>
    <%= render 'userinfo', :user => @user %>
    <% if @user.unverified? && @user == current_user %>
      <div class="profile-message">
        <h2>Not verified!</h2>
        <h3>Your account is restricted, because it has not been verified by an administrator. Talk to an admin in-game to get verified!</h3>
      </div>
    <% end %>
  <% else %>
    <%= render 'userinfo_template' %>
    <div class="profile-message">
      <h2>This account is not registered. :(</h2>
      <% unless logged_in? %><h3>Is it yours? <%= link_to "Register it now!", register_path(:username => params[:id]) %></h3><% end %>
    </div>
  <% end %>
  
  <div class="buffer"></div>
</div>