config/routes.rb
Petyard::Application.routes.draw do
  get 'players_online' => 'home#players_online', :as => :players_online
  get 'map' => 'home#map', :as => :map

  resources :projects do
    member do
      get 'join'
    end

    resources :project_memberships
  end

  resources :mod_messages

  resources :forum_categories, :except => [:show]

  resources :forums do
    resources :topics, :except => [:index] do
      resources :posts, :except => [:index, :show]
    end
  end

  get 'forums/:forum_id/:topic_id/new' => 'posts#new', :as => :new_forum_topic_post
  get 'forums/:forum_id/:topic_id/:id/edit' => 'posts#edit', :as => :edit_forum_topic_post

  get 'forums/:forum_id/new' => 'topics#new', :as => :new_forum_topic
  get 'forums/:forum_id/:id/edit' => 'topics#edit', :as => :edit_forum_topic
  get 'forums/:forum_id/:id' => 'topics#show', :as => :forum_topic
  put 'forums/:forum_id/:id' => 'topics#update'
  delete 'forums/:forum_id/:id' => 'topics#destroy'

  get 'register' => 'users#new', :as => :register
  get 'account' => 'users#edit', :as => :account
  match 'account/:id/remove_avatar' => 'users#remove_avatar', :as => :remove_avatar
  get 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  get 'profile/:id' => 'users#show', :as => :user
  put 'profile/:id' => 'users#update'
  delete 'profile/:id' => 'users#destroy'
  resources :users
  resources :user_sessions

  resources :ranks

  get 'notify' => 'home#notify', :as => :notify

  resources :features
  
  root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Minequery

  def index
    @page_id = 'home'
    @features = Feature.all

    @players_online = get_players_online
  end

  def notify
    unless notice
      redirect_to root_url
    end
  end

  def map
    @page_id = 'map'
  end

  def players_online
    @players_online = get_players_online
  end
end

app/helpers/home_helper.rb
module HomeHelper
  
end

app/views/home/_players_online.html.erb
<% if @server %>
  <%= content_tag :div, id: "players_online", data: { url: players_online_url } do %>
    <ul>
      <% unless players_online.blank? %>
        <% players_online.each do |player_name| %>
          <li class="<%= cycle('','highlight') %>">
            <%= link_to player_name, user_path(player_name) %>
          </li>
        <% end %>
      <% else %>
        <li class="no-players">No players online.</li>
      <% end %>
    </ul>
  <% end %>
<% else %>
  <ul id="serveroffline">
    <li class="align-center">Server offline.</li>
  </ul>
<% end %>

app/views/home/index.html.erb
<% content_for :admin do %>
  <% if can_access(5) %>
    <div id="admin-actions">
      <p>Admin actions for this page:</p>
      <p><%= link_to "Features", features_path %> &#8226; <%= link_to "Users", users_path %> &#8226; <%= link_to "Ranks", ranks_path %></p>
    </div>
  <% end %>
<% end %>

<div id="feature">
  <div class="slides_container">
    <% @features.each do |feature| %>
      <div><%= link_to image_tag(feature.image.url, :alt => feature.title), feature.url%></div>
    <% end %>
  </div>
  <%= link_to "Previous", "javascript:void(0)", :class => "prev" %>
  <%= link_to "Next", "javascript:void(0)", :class => "next" %>
</div>
<div id="sidebar">
  <h1 class="players-online">Players Online</h1>
    <%= render "players_online", :players_online => @players_online %>
  <h1 class="latestforumposts">Latest Forum Posts</h1>
  <ul>
    <% unless latest_forum_posts.blank? %>
      <% latest_forum_posts(5).each do |forum_post| %>
        <li class="<%= cycle('','highlight') %>">
          <a href="<%= url_for forum_topic_path(forum_post.topic.forum, forum_post.topic, :anchor => forum_post.id) %>" class="<%= day_class(forum_post.created_at) %>">
            <%= forum_post.title %>
            <span class="author">posted <span class="<%= day_class(forum_post.created_at) %>"><%= time_ago_in_words(forum_post.created_at) %> ago</span> by <%= forum_post.user.username %></span>
          </a>
        </li>
      <% end %> 
    <% else %>
      <li class="align-center">No forum posts.</li>
    <% end %>
  </ul>
</div>
<div id="news">
  <h1 class="serverupdates">Server Updates</h1>
  <div id="twitter-link">
    <a href="https://twitter.com/mc_petyard" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow @mc_petyard</a>
  </div>
  <%# cache "news#{Date.today}" do %>
    <% Twitter.user_timeline(count: 10, include_rts: false).each do |tweet| %>
      <a href="https://twitter.com/<%= tweet.user.screen_name %>/status/<%= tweet.id %>" class="newsbox">
        <%= image_tag tweet.profile_image_url_https, :alt => tweet.user.screen_name %>
        <%= tweet.text %>
        <span class="date <%= day_class(tweet.created_at) %>"><%= time_ago_in_words(tweet.created_at) %> ago</span>
      </a>
    <% end %>
  <%# end%>
</div>

app/views/home/map.html.erb
<div class="tag"><%= link_to "Full screen", root_url(:port => 8123) %> &#8226; <%= link_to "High-resolution map", (root_url + "high-res-map/") %></div>
<div class="contentbox">
  <object data="http://petyard.net:8123/" width="100%" height="600"></object>
</div>

app/views/home/notify.html.erb
<h2 class="align-center">Notice</h2>
<div class="contentbox notify">
  <p><%=raw notice %></p>
</div>

app/views/home/players_online.js.erb
// alert("test");
$('#players_online').html('<%= j render "players_online", :players_online => @players_online %>');
PlayerPoller.poll();