config/routes.rb
Petyard::Application.routes.draw do
  get 'players_online' => 'home#players_online', :as => :players_online
  get 'map' => 'home#map', :as => :map

  resources :projects do
    member do
      get 'join'
    end

    resources :project_memberships
  end

  resources :mod_messages

  resources :forum_categories, :except => [:show]

  resources :forums do
    resources :topics, :except => [:index] do
      resources :posts, :except => [:index, :show]
    end
  end

  get 'forums/:forum_id/:topic_id/new' => 'posts#new', :as => :new_forum_topic_post
  get 'forums/:forum_id/:topic_id/:id/edit' => 'posts#edit', :as => :edit_forum_topic_post

  get 'forums/:forum_id/new' => 'topics#new', :as => :new_forum_topic
  get 'forums/:forum_id/:id/edit' => 'topics#edit', :as => :edit_forum_topic
  get 'forums/:forum_id/:id' => 'topics#show', :as => :forum_topic
  put 'forums/:forum_id/:id' => 'topics#update'
  delete 'forums/:forum_id/:id' => 'topics#destroy'

  get 'register' => 'users#new', :as => :register
  get 'account' => 'users#edit', :as => :account
  match 'account/:id/remove_avatar' => 'users#remove_avatar', :as => :remove_avatar
  get 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  get 'profile/:id' => 'users#show', :as => :user
  put 'profile/:id' => 'users#update'
  delete 'profile/:id' => 'users#destroy'
  resources :users
  resources :user_sessions

  resources :ranks

  get 'notify' => 'home#notify', :as => :notify

  resources :features
  
  root :to => 'home#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :feature_image, :invite_only, :permalink, :status, :title, :visible, :x_coordinate, :y_coordinate, :z_coordinate

  has_many :project_memberships, :dependent => :destroy
  has_many :users, :through => :project_memberships
  has_attached_file :feature_image, :styles => { :original => "613x613>" }, :dependent => :destroy

  validates :title, :presence => { :message => "* Your project must have a title." }
  validates :title, :uniqueness => { :message => "* There is already a project with this title.", :case_sensitive => false }
  validates_attachment :feature_image, :content_type => { :content_type => "image/jpg", :content_type => "image/png" }, :size => { :in => 0..3.megabytes }

  default_scope :order => ("title asc")
  scope :visible, where(:visible => true)
  def to_param
    permalink
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter(:only => [:new, :create, :edit, :update, :join]) { |b| b.require_power 1 }
  before_filter(:only => [:destroy]) { |b| b.require_power 4 }
  before_filter :set_page_id

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.visible

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.includes(:project_memberships).find_by_permalink(params[:id])

    @founderships = @project.project_memberships.foundership
    @adminships = @project.project_memberships.adminship
    @memberships = @project.project_memberships.membership

    if @project.visible == false && !@project.users.include?(current_user)
      redirect_to projects_url
      return false
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find_by_permalink(params[:id])
    unless (current_user.project_role(@project) == "founder" || current_user.project_role(@project) == "admin") || current_user.has_power(4)
      flash[:notice] = "You do not have permission to edit this project. Please contact an administrator if you feel that this is an error.<br /><br /><a href='#{project_path(@project)}'>Back to project</a>"
      redirect_to notify_path
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.permalink = create_permalink(params[:project][:title])
    @project_membership = @project.project_memberships.build(:user_id => current_user.id, :role => "founder")

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find_by_permalink(params[:id])

    unless (current_user.project_role(@project) == "founder" || current_user.project_role(@project) == "admin") || current_user.has_power(4)
      flash[:notice] = "You do not have permission to edit this project. Please contact an administrator if you feel that this is an error.<br /><br /><a href='#{project_path(@project)}'>Back to project</a>"
      redirect_to notify_path
    end

    @project.permalink = create_permalink(params[:project][:title]) if params[:update_permalink]

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find_by_permalink(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def join
    @project = Project.find_by_permalink(params[:id])

    if @project.users.include?(current_user)
      redirect_to @project
    else
      @project_membership = @project.project_memberships.build(:project_id => @project.id, :user_id => current_user.id)
    end

    respond_to do |format|
      if @project_membership.save
        format.html { redirect_to @project, notice: 'User added.' }
        format.json { render json: @project, status: :created, location: @project }
      end
    end
  end

  protected

  def set_page_id
    @page_id = 'projects'
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, :html => { :multipart => true }, :validate => true) do |f| %>

  <h3>Required information</h3>
  <div class="contentbox">
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <% if controller.action_name == "edit" %>
      <div>
        <%= check_box_tag :update_permalink, true, :checked => true %>
        <%= label_tag :update_permalink, "Update permalink?" %> <small>(Currently: /<span class="highlight"><%= @project.permalink %></span>)</small>
        <br /><br />
      </div>
    <% end %>
  </div>

  <h3>Optional information</h3>
  <div class="contentbox">
    <div class="field">
      <%= f.label :feature_image %><br />
      <%= f.file_field :feature_image %>
      <small>(613 &times; 613 max, 3 megabytes max, jpg or png)</small>
    </div>
    <br />
    <div class="inline-field">
      <%= f.label :x_coordinate, "X-Coordinate" %><br />
      <%= f.text_field :x_coordinate, :maxlength => 5 %>
    </div>
    <div class="inline-field">
      <%= f.label :y_coordinate, "Y-Coordinate" %><br />
      <%= f.text_field :y_coordinate, :maxlength => 5 %>
    </div>
    <div class="inline-field">
      <%= f.label :z_coordinate, "Z-Coordinate" %><br />
      <%= f.text_field :z_coordinate, :maxlength => 5 %>
    </div>
    <br class="break" /><br /><br /><br /><br />
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description %>
    </div>
  </div>

  <h3>Project settings</h3>
  <div class="contentbox">
    <div>
      <%= f.label :visible, "Visibility" %><br />
      <%= f.radio_button :visible, "true" %> Listed
      &nbsp;&nbsp;
      <%= f.radio_button :visible, "false" %> Unlisted
    </div>
    <br />
    <div>
      <%= f.label :invite_only, "Membership" %><br />
      <%= f.radio_button :invite_only, "false" %> Open
      &nbsp;&nbsp;
      <%= f.radio_button :invite_only, "true" %> Invite-only
    </div>
    <br />
    <div class="field">
      <%= f.label :status %><br />
      <%= f.select :status, options_for_select(Petyard::Application.config.project_statuses, @project.status) %>
    </div>
  </div>
  <div class="contentbox">
    <div class="actions">
      <%= f.submit %><br /><br />
      <p class="align-center"><%= link_to "Cancel", projects_path %></p>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="form">
  <h2>Edit project</h2>
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<p class="align-right"><%= link_to "Create project", new_project_path, :class => "button" %></p>

<ul id="projects">
    <% unless @projects.empty? %>
        <% @projects.each do |project| %>
            <li class="<%= cycle('', 'highlight') %>">
                <a href="<%= url_for(project) %>">
                    <% if project.invite_only? %>
                        <span class="membership invite-only">Invite-only</span>
                    <% else %>
                        <span class="membership open">Open to all</span>
                    <% end %>
                    <h3><%= project.title %></h3>
                </a>
            </li>
        <% end %>
    <% else %>
        <li class="no-projects align-center">No projects.</li>
    <% end %>
</ul>

app/views/projects/new.html.erb
<div class="form">
  <h2>Create project</h2>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="project">
  <div class="contentbox project-sidebar align-center">
    <h2><%= @project.title %></h2>
    <p><%= @project.description %></p>
    <% if @project.x_coordinate or @project.y_coordinate or @project.z_coordinate %>
      <h3>Location</h3>
      x: <%= @project.x_coordinate %>, y: <%= @project.y_coordinate %>, z: <%= @project.z_coordinate %><br />
      <%= link_to "map", (root_url(:port => 8123) + "?worldname=world&mapname=flat&zoom=5&x=#{@project.x_coordinate}&y=#{@project.y_coordinate}&z=#{@project.z_coordinate}"), :target => "_blank" %>
    <% end %>
    <br /><br /><br />
    <% if (can_access(1) && !@project.invite_only?) && !@project.users.include?(current_user) %>
      <div class="align-center"><%= link_to "Join project", join_project_path(@project), :class => "button" %></div>
      <br />
    <% else %>
      <% if (can_access(1) && @project.invite_only?) %>
        <div class="align-center"><%= link_to "Invite-only", join_project_path(@project), :class => "button disabled" %></div>
        <br />
      <% end %>
    <% end %>
    <% if (can_access(1) && (current_user.project_role(@project) == "founder" || current_user.project_role(@project) == "admin")) || can_access(4) %>
      <%= link_to "Edit project", edit_project_path(@project) %>
    <% end %>
    <% if can_access(4) %>
      <%= link_to "Delete project", @project, method: :delete, data: { confirm: 'Delete project (this is permanent)?' } %>
    <% end %>
  </div>
  <div class="contentbox project-sidebar">
    <h3>Founders</h3>
    <ul>
      <% unless @founderships.empty? %>
        <% @founderships.each do |membership| %>
          <li>
            <% if can_access(4) %>
              <%= link_to "[remove]", project_project_membership_path(@project, membership), method: :delete, :class => "remove-link" %>
            <% end %>
            <%= link_to image_tag(membership.user.minotar(35), :alt => membership.user.username, :class => "float-left") + membership.user.username, membership.user %> 
          </li>
        <% end %>
      <% else %>
        No founders.
      <% end %>
    </ul>  
    <h3>Admins</h3>
    <ul>
      <% unless @adminships.empty? %>
        <% @adminships.each do |membership| %>
          <li>
            <% if (can_access(1) and current_user.project_role(@project) == "founder") || can_access(4) %>
              <%= link_to "[remove]", project_project_membership_path(@project, membership), method: :delete, :class => "remove-link" %>
            <% end %>
            <%= link_to image_tag(membership.user.minotar(35), :alt => membership.user.username, :class => "float-left") + membership.user.username, membership.user %> 
          </li>
        <% end %>
      <% else %>
        No admins.
      <% end %>
    </ul>
    <h3>Members</h3>
    <ul>
      <% unless @memberships.empty? %>
        <% @memberships.each do |membership| %>
          <li>
            <% if (can_access(1) and (current_user.project_role(@project) == "founder" || current_user.project_role(@project) == "admin")) || can_access(4) %>
              <%= link_to "[remove]", project_project_membership_path(@project, membership), method: :delete, :class => "remove-link" %>
            <% end %>
            <%= link_to image_tag(membership.user.minotar(35), :alt => membership.user.username, :class => "float-left") + membership.user.username, membership.user %> 
          </li>
        <% end %>
      <% else %>
        No members.
      <% end %>
    </ul>
    <% if (can_access(1) && (current_user.project_role(@project) == "founder" || current_user.project_role(@project) == "admin")) || can_access(4) %>
      <div class="align-center"><%= link_to "Add user", new_project_project_membership_path(@project), :class => "button" %></div>
    <% end %>
  </div>
  <div id="project-main">
    <%= image_tag @project.feature_image, :id => "project-feature" if @project.feature_image %>
    <!--
    <div class="contentbox project-gallery">
      Gallery will go here.
    </div>
    -->
  </div>
</div>